version: "3.9"

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"  # API Gateway is exposed on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
    depends_on:
      - cart-service
      - inventory-service
    networks:
      - backend  # Internal network for secure communication

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
    networks:
      - backend

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "4000:4000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
