version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqc
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"  # API Gateway is exposed on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
    depends_on:
      - cart-service
      - inventory-service
    networks:
      - backend  # Internal network for secure communication

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - backend

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge
