version: "3.9"

services:
  order:
    build:
      context: ./order
    container_name: order
    volumes:
      - ./order:/app/order
    ports:
      - "3000:3000"
    networks:
      - backend
  
  payment:
    build:
      context: ./payment
    container_name: payment
    volumes:
      - ./payment:/app/payment
    ports:
      - "3001:3001"
    networks:
      - backend

  product:
    build:
      context: ./product
    container_name: product
    volumes:
      - ./product:/app/product
    ports:
      - "3002:3002"
    networks:
      - backend

  api-gateway:
      image: nginx:latest
      container_name: api-gateway
      ports:
        - "8080:8080"  # API Gateway is exposed on port 8080
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
      depends_on:
        - order
        - payment
        - product
      networks:
        - backend  # Internal network for secure communication

networks:
  backend:
    driver: bridge