events {}

http {
    upstream order_backend {
        server order:3000;
    }

    upstream payment_backend {
        server payment:3001;
    }

    upstream product_backend {
        server product:3002;
    }

    server {
        listen 8080;

        location /api/order/ {
            proxy_pass http://order_backend/;
        }

        location /api/payment/ {
            proxy_pass http://payment_backend/;
        }
        location /api/product/ {
            proxy_pass http://product_backend/;
        }
    }
}
